fix slave output over buffersize
sorenisanerd/gotty pull request #56
Opened 2022-11-12 09:23 UTC by funnywwh

2022-11-25 21:53 UTC, sorenisanerd commented on webtty/webtty.go
> +				maxChunkSize := int(effectiveBufferSize/4) * 3
Oh, that's a good catch!

For compatibility reasons, we don't always use base64 encoding, so this should depend on the encoder being used.

2022-11-25 21:53 UTC, sorenisanerd requested changes
Oh, that's a good catch!

For compatibility reasons, we don't always use base64 encoding, so this should depend on the encoder being used.

2022-11-27 12:43 UTC, funnywwh commented
> Oh, that's a good catch!
> 
> For compatibility reasons, we don't always use base64 encoding, so this should depend on the encoder being used.

So,how to do that?Close?

2022-11-27 17:08 UTC, merged

2022-11-27 17:08 UTC, sorenisanerd commented
I'm sorry. I was wrong. I was thinking about when we talk to the master, not the slave.

Great work. Thanks :)